# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a98eeb593a01d7ea0f96a2bf2346f4e118a01fb9f02a78f84ce640f9f9e4c7f5b7f1a990309e23a607d09c55040ca2bdf8f677c233e0329ba8acc2cc269c5ca

test:
  secret_key_base: ffceccac341b3182d4ab516ce5d18f93fc1ba360573fa7888db998d962a58d933cbb6642c9fcfc43cf284b4a0b0a2828b12bc1901582ad13ff2009b3661a7bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
